"""
class Ui_DataBase(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent=parent)
        self.setupUi(self)

    def setupUi(self, DataBase):
        # DataBase.setObjectName("DataBase")
        # DataBase.resize(906, 640)
        self.layoutWidget = QtWidgets.QWidget(DataBase)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 170, 721, 141))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setVerticalSpacing(34)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 2, 1, 1)
        self.submit = PrimaryPushButton(self.layoutWidget)
        self.submit.setObjectName("submit")
        self.gridLayout.addWidget(self.submit, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.database_username = LineEdit(self.layoutWidget)
        self.database_username.setObjectName("database_username")
        self.gridLayout.addWidget(self.database_username, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.database_url = LineEdit(self.layoutWidget)
        self.database_url.setObjectName("database_url")
        self.gridLayout.addWidget(self.database_url, 1, 0, 1, 1)
        self.database_password = LineEdit(self.layoutWidget)
        self.database_password.setObjectName("database_password")
        self.gridLayout.addWidget(self.database_password, 1, 3, 1, 1)
        self.database_dbname = LineEdit(self.layoutWidget)
        self.database_dbname.setObjectName("database_dbname")
        self.gridLayout.addWidget(self.database_dbname, 1, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 4, 1, 1)
        self.database_port = LineEdit(self.layoutWidget)
        self.database_port.setObjectName("database_port")
        self.gridLayout.addWidget(self.database_port, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 2)
        self.gridLayout.setColumnStretch(3, 2)
        self.gridLayout.setColumnStretch(4, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 3)
        self.label_6 = QtWidgets.QLabel(DataBase)
        self.label_6.setGeometry(QtCore.QRect(110, 120, 721, 25))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(DataBase)
        QtCore.QMetaObject.connectSlotsByName(DataBase)

    def retranslateUi(self, DataBase):
        _translate = QtCore.QCoreApplication.translate
        DataBase.setWindowTitle(_translate("DataBase", "Form"))
        self.label_7.setText(_translate("DataBase", "用户名"))
        self.submit.setText(_translate("DataBase", "确认"))
        self.label.setText(_translate("DataBase", "数据库url"))
        self.label_2.setText(_translate("DataBase", "port"))
        self.label_8.setText(_translate("DataBase", "密码"))
        self.label_9.setText(_translate("DataBase", "数据库名称"))
        self.label_6.setText(_translate("DataBase", "数据库设置"))
"""
