# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled3.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_table_dialog(object):
    def setupUi(self, table_dialog):
        table_dialog.setObjectName("table_dialog")
        table_dialog.resize(1085, 691)
        self.table = TableWidget(table_dialog)
        self.table.setGeometry(QtCore.QRect(50, 90, 381, 461))
        self.table.setObjectName("table")
        self.table.setColumnCount(0)
        self.table.setRowCount(0)
        self.wordcloud = PrimaryPushButton(table_dialog)
        self.wordcloud.setGeometry(QtCore.QRect(470, 170, 153, 32))
        self.wordcloud.setObjectName("wordcloud")
        self.timeline_analysis = PrimaryPushButton(table_dialog)
        self.timeline_analysis.setGeometry(QtCore.QRect(470, 280, 153, 32))
        self.timeline_analysis.setObjectName("timeline_analysis")
        self.gender_analysis = PrimaryPushButton(table_dialog)
        self.gender_analysis.setGeometry(QtCore.QRect(470, 390, 153, 32))
        self.gender_analysis.setObjectName("gender_analysis")
        self.show_label = PixmapLabel(table_dialog)
        self.show_label.setGeometry(QtCore.QRect(650, 70, 401, 481))
        self.show_label.setObjectName("show_label")
        self.save_to_database = PrimaryPushButton(table_dialog)
        self.save_to_database.setGeometry(QtCore.QRect(40, 580, 153, 32))
        self.save_to_database.setObjectName("save_to_database")
        self.cancle = PrimaryPushButton(table_dialog)
        self.cancle.setGeometry(QtCore.QRect(270, 580, 153, 32))
        self.cancle.setObjectName("cancle")
        self.city_hot = PrimaryPushButton(table_dialog)
        self.city_hot.setGeometry(QtCore.QRect(470, 490, 153, 32))
        self.city_hot.setObjectName("city_hot")

        self.retranslateUi(table_dialog)
        QtCore.QMetaObject.connectSlotsByName(table_dialog)

    def retranslateUi(self, table_dialog):
        _translate = QtCore.QCoreApplication.translate
        table_dialog.setWindowTitle(_translate("table_dialog", "Form"))
        self.wordcloud.setText(_translate("table_dialog", "词云分析"))
        self.timeline_analysis.setText(_translate("table_dialog", "时间线统计"))
        self.gender_analysis.setText(_translate("table_dialog", "性别比例分析"))
        self.save_to_database.setText(_translate("table_dialog", "保存到数据库"))
        self.cancle.setText(_translate("table_dialog", "退出"))
        self.city_hot.setText(_translate("table_dialog", "城市热力图"))
from qfluentwidgets import PixmapLabel, PrimaryPushButton, TableWidget
